#Requires AutoHotkey v2.0
global logPath := A_ScriptDir . "\test_trace.log"
try FileDelete(logPath)
FileAppend("START TRACE`n", logPath, "UTF-8")
OnError((thrown, mode) => (FileAppend("AHK ERROR: " . thrown.Message . " (Line " . thrown.Line . ")`n", logPath, "UTF-8"), ExitApp(1)))
#Requires AutoHotkey v2.0
FileAppend("LINE 2`n", logPath, "UTF-8")

logPath := A_ScriptDir . "\test_results.log"
FileAppend("LINE 4`n", logPath, "UTF-8")
try FileDelete(logPath)
FileAppend("LINE 5`n", logPath, "UTF-8")
FileAppend("INIT TEST RUNNER`n", logPath, "UTF-8")
FileAppend("LINE 6`n", logPath, "UTF-8")

#Include "Lib\Globals.ahk"
#Include "Lib\CSVParser.ahk"
#Include "Lib\NumberParser.ahk"
#Include "Lib\MathEvaluator.ahk"
#Include "Lib\Actions_DateTime.ahk"
#Include "Lib\Actions_Text.ahk"
#Include "Lib\Actions_Finance.ahk"
#Include "Lib\Actions_Extraction.ahk"
FileAppend("LINE 15`n", logPath, "UTF-8")

FileAppend("LINE 16`n", logPath, "UTF-8")
FileAppend("INCLUDES LOADED`n", logPath, "UTF-8")
FileAppend("LINE 17`n", logPath, "UTF-8")

FileAppend("LINE 18`n", logPath, "UTF-8")
global PassCount := 0
FileAppend("LINE 19`n", logPath, "UTF-8")
global FailCount := 0
FileAppend("LINE 20`n", logPath, "UTF-8")
global TestReport := ""
FileAppend("LINE 21`n", logPath, "UTF-8")

FileAppend("LINE 22`n", logPath, "UTF-8")
AssertEqual(testCategory, testName, actual, expected) {
FileAppend("LINE 23`n", logPath, "UTF-8")
    global PassCount, FailCount, TestReport
FileAppend("LINE 24`n", logPath, "UTF-8")
    actualStr := String(actual)
FileAppend("LINE 25`n", logPath, "UTF-8")
    expectedStr := String(expected)
FileAppend("LINE 26`n", logPath, "UTF-8")
    
FileAppend("LINE 27`n", logPath, "UTF-8")
    if (actualStr == expectedStr) {
FileAppend("LINE 28`n", logPath, "UTF-8")
        PassCount++
FileAppend("LINE 29`n", logPath, "UTF-8")
        TestReport .= Format("[PASS] {1,-20} | {2,-38} -> '{3}'`n", testCategory, testName, actualStr)
FileAppend("LINE 30`n", logPath, "UTF-8")
    } else {
FileAppend("LINE 31`n", logPath, "UTF-8")
        FailCount++
FileAppend("LINE 32`n", logPath, "UTF-8")
        TestReport .= Format("[FAIL] {1,-20} | {2,-38} -> Expected: '{3}', Got: '{4}'`n", testCategory, testName, expectedStr, actualStr)
FileAppend("LINE 33`n", logPath, "UTF-8")
    }
FileAppend("LINE 34`n", logPath, "UTF-8")
}
FileAppend("LINE 35`n", logPath, "UTF-8")

FileAppend("LINE 36`n", logPath, "UTF-8")
AssertTrue(testCategory, testName, condition) {
FileAppend("LINE 37`n", logPath, "UTF-8")
    AssertEqual(testCategory, testName, condition ? "TRUE" : "FALSE", "TRUE")
FileAppend("LINE 38`n", logPath, "UTF-8")
}
FileAppend("LINE 39`n", logPath, "UTF-8")

FileAppend("LINE 40`n", logPath, "UTF-8")
AssertFalse(testCategory, testName, condition) {
FileAppend("LINE 41`n", logPath, "UTF-8")
    AssertEqual(testCategory, testName, condition ? "TRUE" : "FALSE", "FALSE")
FileAppend("LINE 42`n", logPath, "UTF-8")
}
FileAppend("LINE 43`n", logPath, "UTF-8")

FileAppend("LINE 44`n", logPath, "UTF-8")
FileAppend("SECTION 1`n", logPath, "UTF-8")
FileAppend("LINE 45`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Standard Integer", CleanToMachineNumber("100"), "100")
FileAppend("LINE 46`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Signed Negative", CleanToMachineNumber("-500"), "-500")
FileAppend("LINE 47`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Zero", CleanToMachineNumber("0"), "0")
FileAppend("LINE 48`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Decimal Value", CleanToMachineNumber("125.50"), "125.50")
FileAppend("LINE 49`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Leading Dot", CleanToMachineNumber(".75"), "0.75")
FileAppend("LINE 50`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Accounting Negative", CleanToMachineNumber("(1,500.00)"), "-1500")
FileAppend("LINE 51`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Indian Crore (12 cr)", CleanToMachineNumber("12 cr"), "120000000")
FileAppend("LINE 52`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Indian Crore (2.5 Cr)", CleanToMachineNumber("2.5 Cr"), "25000000")
FileAppend("LINE 53`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Indian Lakh (1.25 Lakh)", CleanToMachineNumber("1.25 Lakh"), "125000")
FileAppend("LINE 54`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Indian Lakh (12 lakh)", CleanToMachineNumber("12 lakh"), "1200000")
FileAppend("LINE 55`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Indian Lac (1.25 lac)", CleanToMachineNumber("1.25 lac"), "125000")
FileAppend("LINE 56`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Thousand (12k)", CleanToMachineNumber("12k"), "12000")
FileAppend("LINE 57`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Thousand (12.5k)", CleanToMachineNumber("12.5k"), "12500")
FileAppend("LINE 58`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Million (12m)", CleanToMachineNumber("12m"), "12000000")
FileAppend("LINE 59`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Million (1.5 million)", CleanToMachineNumber("1.5 million"), "1500000")
FileAppend("LINE 60`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Billion (1.5b)", CleanToMachineNumber("1.5b"), "1500000000")
FileAppend("LINE 61`n", logPath, "UTF-8")
AssertEqual("NumberParser", "Rupees Symbol (₹1,25,000)", CleanToMachineNumber("₹1,25,000"), "125000")
FileAppend("LINE 62`n", logPath, "UTF-8")
AssertEqual("NumberParser", "INR Prefix (INR 2.5 Cr)", CleanToMachineNumber("INR 2.5 Cr"), "25000000")
FileAppend("LINE 63`n", logPath, "UTF-8")
AssertEqual("NumberParser", "USD ($1,500.50)", CleanToMachineNumber("$1,500.50"), "1500.50")
FileAppend("LINE 64`n", logPath, "UTF-8")
AssertEqual("NumberParser", "European Format (1.250,50)", CleanToMachineNumber("1.250,50"), "1250.50")
FileAppend("LINE 65`n", logPath, "UTF-8")
AssertFalse("NumberParser", "Empty String Invalid", ParseNumberOrCurrency("").isValid)
FileAppend("LINE 66`n", logPath, "UTF-8")
AssertFalse("NumberParser", "Pure Text Invalid", ParseNumberOrCurrency("hello world").isValid)
FileAppend("LINE 67`n", logPath, "UTF-8")
AssertFalse("NumberParser", "Multiple Dots Invalid", ParseNumberOrCurrency("1.2.3").isValid)
FileAppend("LINE 68`n", logPath, "UTF-8")

FileAppend("LINE 69`n", logPath, "UTF-8")
FileAppend("SECTION 2`n", logPath, "UTF-8")
FileAppend("LINE 70`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Zero", NumberToIndianWords("0"), "Rupees Zero Only")
FileAppend("LINE 71`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Zero Decimal (0.00)", NumberToIndianWords("0.00"), "Rupees Zero Only")
FileAppend("LINE 72`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Paise Only (0.50)", NumberToIndianWords("0.50"), "Fifty Paise Only")
FileAppend("LINE 73`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Single Digit", NumberToIndianWords("1"), "Rupees One Only")
FileAppend("LINE 74`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Teens (15)", NumberToIndianWords("15"), "Rupees Fifteen Only")
FileAppend("LINE 75`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Tens (99)", NumberToIndianWords("99"), "Rupees Ninety-Nine Only")
FileAppend("LINE 76`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Hundreds (100)", NumberToIndianWords("100"), "Rupees One Hundred Only")
FileAppend("LINE 77`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Hundreds with units (105)", NumberToIndianWords("105"), "Rupees One Hundred Five Only")
FileAppend("LINE 78`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Thousands (1000)", NumberToIndianWords("1000"), "Rupees One Thousand Only")
FileAppend("LINE 79`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Thousands with units (1005)", NumberToIndianWords("1005"), "Rupees One Thousand Five Only")
FileAppend("LINE 80`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Lakh (100000)", NumberToIndianWords("100000"), "Rupees One Lakh Only")
FileAppend("LINE 81`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Crore (10000000)", NumberToIndianWords("10000000"), "Rupees One Crore Only")
FileAppend("LINE 82`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Unit Word (1.25 lakh)", NumberToIndianWords("1.25 lakh"), "Rupees One Lakh Twenty-Five Thousand Only")
FileAppend("LINE 83`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Unit Word (2.5 cr)", NumberToIndianWords("2.5 cr"), "Rupees Two Crore Fifty Lakh Only")
FileAppend("LINE 84`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Unit Word (12 crore)", NumberToIndianWords("12 crore"), "Rupees Twelve Crore Only")
FileAppend("LINE 85`n", logPath, "UTF-8")
AssertEqual("IndianWords", "Amount with paise (154320.50)", NumberToIndianWords("154320.50"), "Rupees One Lakh Fifty-Four Thousand Three Hundred Twenty and Fifty Paise Only")
FileAppend("LINE 86`n", logPath, "UTF-8")
AssertEqual("IndianWords", "INR Prefix (INR 1.25 Lakh)", NumberToIndianWords("INR 1.25 Lakh"), "Rupees One Lakh Twenty-Five Thousand Only")
FileAppend("LINE 87`n", logPath, "UTF-8")

FileAppend("LINE 88`n", logPath, "UTF-8")
FileAppend("SECTION 3`n", logPath, "UTF-8")
FileAppend("LINE 89`n", logPath, "UTF-8")
AssertEqual("Commas", "Indian 1000", FormatIndianCommas("1000"), "1,000.00")
FileAppend("LINE 90`n", logPath, "UTF-8")
AssertEqual("Commas", "Indian 10000", FormatIndianCommas("10000"), "10,000.00")
FileAppend("LINE 91`n", logPath, "UTF-8")
AssertEqual("Commas", "Indian 100000", FormatIndianCommas("100000"), "1,00,000.00")
FileAppend("LINE 92`n", logPath, "UTF-8")
AssertEqual("Commas", "Indian 12345678", FormatIndianCommas("12345678"), "1,23,45,678.00")
FileAppend("LINE 93`n", logPath, "UTF-8")
AssertEqual("Commas", "Indian Unit (12 cr)", FormatIndianCommas("12 cr"), "12,00,00,000.00")
FileAppend("LINE 94`n", logPath, "UTF-8")
AssertEqual("Commas", "Indian Unit (1.25 lakh)", FormatIndianCommas("1.25 lakh"), "1,25,000.00")
FileAppend("LINE 95`n", logPath, "UTF-8")
AssertEqual("Commas", "Indian Negative (-5000)", FormatIndianCommas("-5000"), "-5,000.00")
FileAppend("LINE 96`n", logPath, "UTF-8")
AssertEqual("Commas", "Indian No Decimals", FormatIndianCommas("12345678", false), "1,23,45,678")
FileAppend("LINE 97`n", logPath, "UTF-8")
AssertEqual("Commas", "International 1000000", FormatInternationalCommas("1000000"), "1,000,000.00")
FileAppend("LINE 98`n", logPath, "UTF-8")
AssertEqual("Commas", "International 12345678", FormatInternationalCommas("12345678"), "12,345,678.00")
FileAppend("LINE 99`n", logPath, "UTF-8")
AssertEqual("Commas", "International Unit (1.5m)", FormatInternationalCommas("1.5m"), "1,500,000.00")
FileAppend("LINE 100`n", logPath, "UTF-8")

FileAppend("LINE 101`n", logPath, "UTF-8")
FileAppend("SECTION 4`n", logPath, "UTF-8")
FileAppend("LINE 102`n", logPath, "UTF-8")
AssertEqual("MathEval", "Arithmetic (1500*1.18+450)", SafeEvaluateMath("1500 * 1.18 + 450").resultStr, "2220")
FileAppend("LINE 103`n", logPath, "UTF-8")
AssertEqual("MathEval", "Percentage Add (1500 + 18%)", SafeEvaluateMath("1500 + 18%").resultStr, "1770")
FileAppend("LINE 104`n", logPath, "UTF-8")
AssertEqual("MathEval", "Percentage Sub (1500 - 10%)", SafeEvaluateMath("1500 - 10%").resultStr, "1350")
FileAppend("LINE 105`n", logPath, "UTF-8")
AssertEqual("MathEval", "Percentage Mult (500 * 20%)", SafeEvaluateMath("500 * 20%").resultStr, "100")
FileAppend("LINE 106`n", logPath, "UTF-8")
AssertEqual("MathEval", "Exponentiation (2 ^ 3)", SafeEvaluateMath("2 ^ 3").resultStr, "8")
FileAppend("LINE 107`n", logPath, "UTF-8")
AssertEqual("MathEval", "Power (2 ** 4)", SafeEvaluateMath("2 ** 4").resultStr, "16")
FileAppend("LINE 108`n", logPath, "UTF-8")
AssertEqual("MathEval", "Multiply x notation (1500x300x87)", SafeEvaluateMath("1500x300x87").resultStr, "39150000")
FileAppend("LINE 109`n", logPath, "UTF-8")
AssertEqual("MathEval", "Division Symbol (100 ÷ 4)", SafeEvaluateMath("100 ÷ 4").resultStr, "25")
FileAppend("LINE 110`n", logPath, "UTF-8")
AssertEqual("MathEval", "Brackets ([10 + 20] * {5 - 2})", SafeEvaluateMath("[10 + 20] * {5 - 2}").resultStr, "90")
FileAppend("LINE 111`n", logPath, "UTF-8")
AssertEqual("MathEval", "Currency Stripping (₹1500 + $500)", SafeEvaluateMath("₹1500 + $500").resultStr, "2000")
FileAppend("LINE 112`n", logPath, "UTF-8")
AssertEqual("MathEval", "Trailing Equals (1500 + 500 = ?)", SafeEvaluateMath("1500 + 500 = ?").resultStr, "2000")
FileAppend("LINE 113`n", logPath, "UTF-8")
AssertEqual("MathEval", "Multi-group commas (1,000,000 / 2)", SafeEvaluateMath("1,000,000 / 2").resultStr, "500000")
FileAppend("LINE 114`n", logPath, "UTF-8")
AssertFalse("MathEval", "Division by zero fails safely", SafeEvaluateMath("100 / 0").success)
FileAppend("LINE 115`n", logPath, "UTF-8")
AssertFalse("MathEval", "Invalid string fails safely", SafeEvaluateMath("invalid text expression").success)
FileAppend("LINE 116`n", logPath, "UTF-8")

FileAppend("LINE 117`n", logPath, "UTF-8")
FileAppend("SECTION 5`n", logPath, "UTF-8")
FileAppend("LINE 118`n", logPath, "UTF-8")
AssertEqual("Finance", "FY Aug 2026 (Q2)", ResolveIndianFinancialYear("2026-08-24"), "FY 2026-27 (Q2)")
FileAppend("LINE 119`n", logPath, "UTF-8")
AssertEqual("Finance", "FY Jan 2026 (Q4)", ResolveIndianFinancialYear("2026-01-15"), "FY 2025-26 (Q4)")
FileAppend("LINE 120`n", logPath, "UTF-8")
AssertEqual("Finance", "FY Apr 2026 (Q1)", ResolveIndianFinancialYear("2026-04-01"), "FY 2026-27 (Q1)")
FileAppend("LINE 121`n", logPath, "UTF-8")
AssertEqual("Finance", "FY Mar 2026 (Q4)", ResolveIndianFinancialYear("2026-03-31"), "FY 2025-26 (Q4)")
FileAppend("LINE 122`n", logPath, "UTF-8")
AssertEqual("Finance", "FY Nov 2026 (Q3)", ResolveIndianFinancialYear("2026-11-15"), "FY 2026-27 (Q3)")
FileAppend("LINE 123`n", logPath, "UTF-8")

FileAppend("LINE 124`n", logPath, "UTF-8")
FileAppend("SECTION 6`n", logPath, "UTF-8")
FileAppend("LINE 125`n", logPath, "UTF-8")
revGst := CalculateReverseGST(118000, 18)
FileAppend("LINE 126`n", logPath, "UTF-8")
AssertTrue("Finance", "Reverse GST Base 1,00,000", InStr(revGst, "Taxable Base: ₹1,00,000.00"))
FileAppend("LINE 127`n", logPath, "UTF-8")
AssertTrue("Finance", "Reverse GST Total GST 18,000", InStr(revGst, "Total GST (18%): ₹18,000.00"))
FileAppend("LINE 128`n", logPath, "UTF-8")
cagrReport := CalculateCAGR(1000000, 2000000, 5)
FileAppend("LINE 129`n", logPath, "UTF-8")
AssertTrue("Finance", "CAGR rate 14.87%", InStr(cagrReport, "CAGR): 14.87%"))
FileAppend("LINE 130`n", logPath, "UTF-8")
AssertTrue("Finance", "CAGR absolute return +100%", InStr(cagrReport, "Absolute Return: +100.00%"))
FileAppend("LINE 131`n", logPath, "UTF-8")

FileAppend("LINE 132`n", logPath, "UTF-8")
FileAppend("SECTION 7`n", logPath, "UTF-8")
FileAppend("LINE 133`n", logPath, "UTF-8")
AssertEqual("Extraction", "PAN Extraction", ExtractPan("My PAN is ABCDE1234F and XYZPK9876Q."), "ABCDE1234F`nXYZPK9876Q")
FileAppend("LINE 134`n", logPath, "UTF-8")
AssertEqual("Extraction", "GSTIN Extraction", ExtractGstin("GSTIN: 07AAAAA0000A1Z5."), "07AAAAA0000A1Z5")
FileAppend("LINE 135`n", logPath, "UTF-8")
AssertEqual("Extraction", "Email Extraction", ExtractEmails("test@example.com and support@company.co.in"), "test@example.com`nsupport@company.co.in")
FileAppend("LINE 136`n", logPath, "UTF-8")
AssertEqual("Extraction", "Phone Extraction", ExtractPhones("Call +91 9876543210 or 7983604887"), "+91 9876543210`n7983604887")
FileAppend("LINE 137`n", logPath, "UTF-8")
AssertEqual("Extraction", "URL Extraction", ExtractUrls("Visit https://google.com and http://example.com/test?q=1."), "https://google.com`nhttp://example.com/test?q=1")
FileAppend("LINE 138`n", logPath, "UTF-8")
AssertTrue("Extraction", "Valid Calendar Date (21-Aug-2026)", IsValidCalendarDate("21-Aug-2026"))
FileAppend("LINE 139`n", logPath, "UTF-8")
AssertTrue("Extraction", "Valid Leap Date (29-Feb-2024)", IsValidCalendarDate("29-Feb-2024"))
FileAppend("LINE 140`n", logPath, "UTF-8")
AssertFalse("Extraction", "Invalid Non-Leap Date (29-Feb-2025)", IsValidCalendarDate("29-Feb-2025"))
FileAppend("LINE 141`n", logPath, "UTF-8")
AssertFalse("Extraction", "Invalid Date (31/02/2026)", IsValidCalendarDate("31/02/2026"))
FileAppend("LINE 142`n", logPath, "UTF-8")
AssertFalse("Extraction", "Invalid Date (99/99/9999)", IsValidCalendarDate("99/99/9999"))
FileAppend("LINE 143`n", logPath, "UTF-8")

FileAppend("LINE 144`n", logPath, "UTF-8")
FileAppend("SECTION 8`n", logPath, "UTF-8")
FileAppend("LINE 145`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Case Cycle lower->Title", CycleTextCase("hello"), "Hello")
FileAppend("LINE 146`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Case Cycle Title->UPPER", CycleTextCase("Hello"), "HELLO")
FileAppend("LINE 147`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Case Cycle UPPER->lower", CycleTextCase("HELLO"), "hello")
FileAppend("LINE 148`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Sentence Case", ToSentenceCase("hello world. this is a test."), "Hello world. This is a test.")
FileAppend("LINE 149`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Snake Case", ToDelimitedCase("Hello World Test", "_"), "hello_world_test")
FileAppend("LINE 150`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Kebab Case", ToDelimitedCase("Hello World Test", "-"), "hello-world-test")
FileAppend("LINE 151`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Camel Case", ToCamelCase("hello world test"), "helloWorldTest")
FileAppend("LINE 152`n", logPath, "UTF-8")
AssertEqual("TextTransform", "SQL IN List", FormatSqlInList("101`n102`n103"), "('101', '102', '103')")
FileAppend("LINE 153`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Bullet List", FormatBulletList("Apple`nBanana"), "• Apple`n• Banana")
FileAppend("LINE 154`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Numbered List", FormatNumberedList("Apple`nBanana"), "1. Apple`n2. Banana")
FileAppend("LINE 155`n", logPath, "UTF-8")
AssertEqual("TextTransform", "Checklist", FormatChecklist("Apple`nBanana"), "- [ ] Apple`n- [ ] Banana")
FileAppend("LINE 156`n", logPath, "UTF-8")

FileAppend("LINE 157`n", logPath, "UTF-8")
FileAppend("SECTION 9`n", logPath, "UTF-8")
FileAppend("LINE 158`n", logPath, "UTF-8")
csvSample := "id,task,created`n1,`"Review contract, sign and send`",2026-08-24`n2,`"Line 1`nLine 2`",2026-08-24"
FileAppend("LINE 159`n", logPath, "UTF-8")
parsedRows := ParseFullCSV(csvSample)
FileAppend("LINE 160`n", logPath, "UTF-8")
AssertEqual("CSVParser", "Row Count", parsedRows.Length, 3)
FileAppend("LINE 161`n", logPath, "UTF-8")
AssertEqual("CSVParser", "Quoted Comma Field", parsedRows[2][2], "Review contract, sign and send")
FileAppend("LINE 162`n", logPath, "UTF-8")
AssertEqual("CSVParser", "Multiline Field", parsedRows[3][2], "Line 1`nLine 2")
FileAppend("LINE 163`n", logPath, "UTF-8")

FileAppend("LINE 164`n", logPath, "UTF-8")
summaryHeader := "================================================================================`n"
FileAppend("LINE 165`n", logPath, "UTF-8")
              . "               OFFICE PRODUCTIVITY HUB - TEST SUITE EXECUTION REPORT            `n"
FileAppend("LINE 166`n", logPath, "UTF-8")
              . "================================================================================`n"
FileAppend("LINE 167`n", logPath, "UTF-8")
              . Format("Total Tests Executed: {1}`nPassed: {2}`nFailed: {3}`nSuccess Rate: {4:0.1f}%`n`n", 
FileAppend("LINE 168`n", logPath, "UTF-8")
                       PassCount + FailCount, PassCount, FailCount, (PassCount / (PassCount + FailCount)) * 100)
FileAppend("LINE 169`n", logPath, "UTF-8")

FileAppend("LINE 170`n", logPath, "UTF-8")
fullReport := summaryHeader . TestReport
FileAppend("LINE 171`n", logPath, "UTF-8")
FileAppend(fullReport, logPath, "UTF-8")
FileAppend("LINE 172`n", logPath, "UTF-8")
FileAppend("ALL TESTS COMPLETED SUCCESSFULLY`n", logPath, "UTF-8")
FileAppend("LINE 173`n", logPath, "UTF-8")
ExitApp(FailCount > 0 ? 1 : 0)
FileAppend("LINE 174`n", logPath, "UTF-8")

